"use client";

import { useMemo, useState } from "react";
import type { DemoBundle, ScreenSpec } from "@/lib/schemas/screen";
import { BlockRenderer } from "./block-renderer";

export function PublicDemo({ bundle }: { bundle: DemoBundle }) {
  const [active, setActive] = useState<string>(bundle.startScreen);
  const screenIndex: Record<string, ScreenSpec> = useMemo(
    () => Object.fromEntries(bundle.screens.map((s) => [s.name, s])),
    [bundle]
  );
  const screen = screenIndex[active] ?? bundle.screens[0];

  return (
    <div className="mx-auto max-w-5xl px-6 py-10">
      <header className="mb-6">
        <div className="text-xs font-semibold uppercase tracking-widest text-primary">Demo</div>
        <h1 className="text-2xl font-semibold tracking-tight">{bundle.appName}</h1>
        <p className="text-sm text-muted-foreground">{bundle.tagline}</p>
      </header>
      <div className="grid gap-4 md:grid-cols-[180px_1fr]">
        <nav className="rounded-xl border bg-white p-2">
          <ul className="space-y-1">
            {bundle.screens.map((s) => (
              <li key={s.name}>
                <button
                  onClick={() => setActive(s.name)}
                  className={`w-full rounded-md px-3 py-2 text-left text-sm ${
                    active === s.name ? "bg-primary text-primary-foreground" : "hover:bg-accent"
                  }`}
                >
                  {s.navLabel}
                </button>
              </li>
            ))}
          </ul>
        </nav>
        <div className="rounded-xl border bg-white p-5">
          <BlockRenderer spec={screen} screenIndex={screenIndex} onNavigate={(n) => setActive(n)} />
        </div>
      </div>
      <footer className="mt-6 text-center text-xs text-muted-foreground">
        Generated by <span className="font-semibold">Spark</span>
      </footer>
    </div>
  );
}
